# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

WAIT_TIME = 1

class CreationTournoi(unittest.TestCase):
    def setUp(self):
        profile = webdriver.FirefoxProfile("/home/florian/.mozilla/firefox/mwad0hks.default")
        self.driver = webdriver.Firefox(profile)
        self.driver.implicitly_wait(30)
        self.base_url = "http://localhost:8000"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_creation_tournoi(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        driver.find_element_by_link_text("Accueil").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_name("password").clear()
        driver.find_element_by_name("password").send_keys("azerty123")
        time.sleep(WAIT_TIME)
        driver.find_element_by_name("username").clear()
        driver.find_element_by_name("username").send_keys("ProjectLeader")
        driver.find_element_by_xpath("//button[@type='submit']").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_link_text("Staff").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("li.dropdown.open > ul.dropdown-menu > li > a").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//button[@onclick=\"location.href='/staff/tournois/Double%20mixte_Minimes';\"]").click()
        driver.find_element_by_css_selector("#zone2515 > div.row > div.col-xs-10").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#zone2542 > div.row > div.col-xs-10").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#zone2562 > div.row > div.col-xs-10").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#zone2544 > div.row > div.col-xs-10").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("(//button[@type='button'])[4]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("(//button[@type='button'])[8]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//a[@onclick=\"setInfoTerrain('Majory','Brique','Ouvert',' Aven Ackers, 206<br>9552 Borsbeke','44','100/Tournoi des familles/Samedi|','3');\"]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='zone2528']/div/div[2]/a/b/i").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("errorTerrain1").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("errorTerrain1").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("save_button").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("(//button[@type='button'])[9]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("yesModel").click()
        time.sleep(WAIT_TIME)
        driver.get(self.base_url + '/staff/tournois/poules/Double%20mixte_Minimes')
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//button[@onclick=\"location.href='/staff/tournois/poules/scores/117';\"]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_name("2512-2516").clear()
        driver.find_element_by_name("2512-2516").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys("2")
        driver.find_element_by_name("2512-2517").clear()
        driver.find_element_by_name("2512-2517").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[5]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[5]").send_keys("1")
        driver.find_element_by_name("2512-2528").clear()
        driver.find_element_by_name("2512-2528").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[7]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[7]").send_keys("2")
        driver.find_element_by_name("2512-2542").clear()
        driver.find_element_by_name("2512-2542").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[9]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[9]").send_keys("2")
        driver.find_element_by_name("2516-2517").clear()
        driver.find_element_by_name("2516-2517").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[13]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[13]").send_keys("1")
        driver.find_element_by_name("2516-2528").clear()
        driver.find_element_by_name("2516-2528").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[15]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[15]").send_keys("2")
        driver.find_element_by_name("2516-2542").clear()
        driver.find_element_by_name("2516-2542").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[17]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[17]").send_keys("2")
        driver.find_element_by_name("2517-2528").clear()
        driver.find_element_by_name("2517-2528").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[23]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[23]").send_keys("1")
        driver.find_element_by_name("2517-2542").clear()
        driver.find_element_by_name("2517-2542").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[25]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[25]").send_keys("1")
        driver.find_element_by_name("2528-2542").clear()
        driver.find_element_by_name("2528-2542").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[33]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[33]").send_keys("2")
        driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
        time.sleep(WAIT_TIME*5)
        driver.find_element_by_id("yesModal").click()
        time.sleep(WAIT_TIME)
        driver.get(self.base_url + "/staff/tournois/poules/scores/118")
        driver.find_element_by_name("2515-2539").clear()
        driver.find_element_by_name("2515-2539").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys("1")
        driver.find_element_by_name("2515-2545").clear()
        driver.find_element_by_name("2515-2545").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[5]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[5]").send_keys("2")
        driver.find_element_by_name("2515-2555").clear()
        driver.find_element_by_name("2515-2555").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[7]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[7]").send_keys("2")
        driver.find_element_by_name("2515-2562").clear()
        driver.find_element_by_name("2515-2562").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[9]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[9]").send_keys("1")
        driver.find_element_by_name("2539-2545").clear()
        driver.find_element_by_name("2539-2545").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[13]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[13]").send_keys("1")
        driver.find_element_by_name("2539-2555").clear()
        driver.find_element_by_name("2539-2555").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[15]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[15]").send_keys("2")
        driver.find_element_by_name("2539-2562").clear()
        driver.find_element_by_name("2539-2562").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[17]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[17]").send_keys("0")
        driver.find_element_by_name("2545-2555").clear()
        driver.find_element_by_name("2545-2555").send_keys("0")
        driver.find_element_by_xpath("(//input[@type='text'])[23]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[23]").send_keys("2")
        driver.find_element_by_name("2545-2562").clear()
        driver.find_element_by_name("2545-2562").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[25]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[25]").send_keys("0")
        driver.find_element_by_name("2555-2562").clear()
        driver.find_element_by_name("2555-2562").send_keys("0")
        driver.find_element_by_xpath("(//input[@type='text'])[33]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[33]").send_keys("1")
        driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
        time.sleep(WAIT_TIME*5)
        driver.find_element_by_id("yesModal").click()
        time.sleep(WAIT_TIME)
        driver.get(self.base_url + "/staff/tournois/poules/scores/119")
        driver.find_element_by_name("2544-2561").clear()
        driver.find_element_by_name("2544-2561").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[3]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[3]").send_keys("1")
        driver.find_element_by_name("2544-2563").clear()
        driver.find_element_by_name("2544-2563").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[5]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[5]").send_keys("0")
        driver.find_element_by_name("2544-2565").clear()
        driver.find_element_by_name("2544-2565").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[7]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[7]").send_keys("2")
        driver.find_element_by_name("2561-2563").clear()
        driver.find_element_by_name("2561-2563").send_keys("1")
        driver.find_element_by_xpath("(//input[@type='text'])[11]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[11]").send_keys("2")
        driver.find_element_by_name("2561-2565").clear()
        driver.find_element_by_name("2561-2565").send_keys("2")
        driver.find_element_by_xpath("(//input[@type='text'])[13]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[13]").send_keys("1")
        driver.find_element_by_name("2563-2565").clear()
        driver.find_element_by_name("2563-2565").send_keys("0")
        driver.find_element_by_xpath("(//input[@type='text'])[19]").clear()
        driver.find_element_by_xpath("(//input[@type='text'])[19]").send_keys("2")
        driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
        driver.find_element_by_id("yesModal").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("(//button[@id='treeButton'])[2]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//a[@onclick=\"checkBox('2515')\"]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//a[@onclick=\"checkBox('2515')\"]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='119']/a[2]/div/div").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='119']/a[2]/div/div").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//a[@onclick=\"checkBox('2562')\"]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("(//button[@type='button'])[3]").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("buttonFirstModal").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("div.col-sm-4 > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("create_tree").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div/div[2]/div/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("2")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("1")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div[2]/div[2]/div/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("1")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("2")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div/div[3]/div[2]/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("2")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("0")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div/div[4]/div/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("1")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("2")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div[2]/div[4]/div/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("2")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("0")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//div[@id='my_gracket']/div[3]/div[2]/div/h3").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_id("inputTeam1").clear()
        driver.find_element_by_id("inputTeam1").send_keys("1")
        driver.find_element_by_id("inputTeam2").clear()
        driver.find_element_by_id("inputTeam2").send_keys("2")
        time.sleep(WAIT_TIME)
        driver.find_element_by_css_selector("#scoreModal > div.modal-dialog > div.modal-content > div.modal-body > ul.list-inline.text-center > li > button.btn.btn-default").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_name("action").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_link_text("Accueil").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_link_text(u"Voir les résultats de l'année précédente").click()
        time.sleep(WAIT_TIME)
        driver.find_element_by_xpath("//button[@onclick=\"window.open('/resultat','_self')\"]").click()
        time.sleep(WAIT_TIME)
        # ERROR: Caught exception [ERROR: Unsupported command [waitForPopUp | _self | 30000]]
        driver.find_element_by_link_text(u"Résultats de l'édition 42 (2016)").click()
        time.sleep(WAIT_TIME*10)
        driver.close()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
